### ISSUE TITLE
CC: Restitched 1.101.0 Requires version 0.51.1 or later of fabric?

### ISSUE THREAD

**Issue by Auhrii** [cc-tweaked/cc-restitched#111]
Attempting to run Minecraft 1.19 with Fabric Loader version 0.14.8 (which is the latest at the time of writing) and CC: Restitched 1.101.0 yields the following error:

![image](https://user-images.githubusercontent.com/25776947/174875116-b413453c-bb6c-40d9-a4c3-b36a0c6506fc.png)

The problem here is that both the Fabric Installer (for the vanilla launcher) and the MultiMC Fabric listings both say the newest version of Fabric is 0.14.8 - it seems no 0.51.1 exists anywhere.

Here's the error from copying:

> Incompatible mod set!
> net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
> A potential solution has been determined:
> 	 - Install fabric, version 0.51.1 or later.
> Unmet dependency listing:
> 	 - Mod 'CC: Restitched' (computercraft) 1.101.0 requires version 0.51.1 or later of fabric, which is missing!
> 	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
> 	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
> 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
> 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
> 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
> 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
> 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
> 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
>

**Comment by Auhrii** [comment]
It seems the Fabric Loader for whatever reason doesn't include the Fabric API; I was under the impression the loader installer was just analogous to the Forge installer in that it created a profile and dropped the API in for you. Closing this issue.
