### ISSUE TITLE
[server] not compatible with HardcoreQuestingMod (HQM)

### ISSUE THREAD

**Issue by MSandro** [cc-tweaked/cc-restitched#21]
## Useful information to include:
 - Minecraft version 1.17.1
 - CC: Restitched version 1.97.2
 - Logs:
 ```
Exception in thread "main" [11:54:09] [main/INFO]: [STDERR]: java.lang.RuntimeException: Failed to setup Fabric server environment!
[11:54:09] [main/INFO]: [STDERR]:       at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:58)
[11:54:09] [main/INFO]: [STDERR]: Caused by: java.lang.RuntimeException: java.lang.RuntimeException: An exception occurred when launching the server!
[11:54:09] [main/INFO]: [STDERR]:       at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:116)
[11:54:09] [main/INFO]: [STDERR]:       at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:56)
[11:54:09] [main/INFO]: [STDERR]: Caused by: java.lang.RuntimeException: An exception occurred when launching the server!
[11:54:09] [main/INFO]: [STDERR]:       at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:70)
[11:54:09] [main/INFO]: [STDERR]:       at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:114)
[11:54:09] [main/INFO]: [STDERR]:       ... 1 more
[11:54:09] [main/INFO]: [STDERR]: Caused by: java.lang.reflect.InvocationTargetException
[11:54:09] [main/INFO]: [STDERR]:       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[11:54:09] [main/INFO]: [STDERR]:       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
[11:54:09] [main/INFO]: [STDERR]:       at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[11:54:09] [main/INFO]: [STDERR]:       at java.base/java.lang.reflect.Method.invoke(Method.java:567)
[11:54:09] [main/INFO]: [STDERR]:       at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:68)
[11:54:09] [main/INFO]: [STDERR]:       ... 2 more
[11:54:09] [main/INFO]: [STDERR]: Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
[11:54:09] [main/INFO]: [STDERR]:       at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:236)
[11:54:09] [main/INFO]: [STDERR]:       at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
[11:54:09] [main/INFO]: [STDERR]:       at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:28)
[11:54:09] [main/INFO]: [STDERR]:       ... 7 more
[11:54:09] [main/INFO]: [STDERR]: Caused by: java.lang.reflect.InvocationTargetException
[11:54:09] [main/INFO]: [STDERR]:       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[11:54:09] [main/INFO]: [STDERR]:       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
[11:54:09] [main/INFO]: [STDERR]:       at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[11:54:09] [main/INFO]: [STDERR]:       at java.base/java.lang.reflect.Method.invoke(Method.java:567)
[11:54:09] [main/INFO]: [STDERR]:       at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
[11:54:09] [main/INFO]: [STDERR]:       ... 9 more
[11:54:09] [main/INFO]: [STDERR]: Caused by: java.lang.ExceptionInInitializerError
[11:54:09] [main/INFO]: [STDERR]:       at net.minecraft.class_2588.method_11025(class_2588.java:42)
[11:54:09] [main/INFO]: [STDERR]:       at net.minecraft.class_2588.method_27659(class_2588.java:143)
[11:54:09] [main/INFO]: [STDERR]:       at net.minecraft.class_2561.method_27657(class_2561.java:96)
[11:54:09] [main/INFO]: [STDERR]:       at net.minecraft.class_5348.getString(class_5348.java:91)
[11:54:09] [main/INFO]: [STDERR]:       at net.minecraft.class_2561.getString(class_2561.java:39)
[11:54:09] [main/INFO]: [STDERR]:       at com.mojang.brigadier.exceptions.CommandSyntaxException.<init>(CommandSyntaxException.java:27)
[11:54:09] [main/INFO]: [STDERR]:       at com.mojang.brigadier.exceptions.SimpleCommandExceptionType.createWithContext(SimpleCommandExceptionType.java:21)
[11:54:09] [main/INFO]: [STDERR]:       at com.mojang.brigadier.StringReader.readDouble(StringReader.java:142)
[11:54:09] [main/INFO]: [STDERR]:       at net.minecraft.class_2278.method_9743(class_2278.java:41)
[11:54:09] [main/INFO]: [STDERR]:       at net.minecraft.class_2280.method_9750(class_2280.java:87)
[11:54:09] [main/INFO]: [STDERR]:       at net.minecraft.class_2277.method_9738(class_2277.java:54)
[11:54:09] [main/INFO]: [STDERR]:       at net.minecraft.class_2277.parse(class_2277.java:21)
[11:54:09] [main/INFO]: [STDERR]:       at com.mojang.brigadier.tree.ArgumentCommandNode.isValidInput(ArgumentCommandNode.java:91)
[11:54:09] [main/INFO]: [STDERR]:       at com.mojang.brigadier.tree.CommandNode.findAmbiguities(CommandNode.java:102)
[11:54:09] [main/INFO]: [STDERR]:       at com.mojang.brigadier.tree.CommandNode.findAmbiguities(CommandNode.java:113)
[11:54:09] [main/INFO]: [STDERR]:       at com.mojang.brigadier.tree.CommandNode.findAmbiguities(CommandNode.java:113)
[11:54:09] [main/INFO]: [STDERR]:       at com.mojang.brigadier.CommandDispatcher.findAmbiguities(CommandDispatcher.java:695)
[11:54:09] [main/INFO]: [STDERR]:       at net.minecraft.class_2170.<init>(class_2170.java:235)
[11:54:09] [main/INFO]: [STDERR]:       at net.minecraft.class_5350.<init>(class_5350.java:39)
[11:54:09] [main/INFO]: [STDERR]:       at net.minecraft.class_5350.method_29466(class_5350.java:88)
[11:54:09] [main/INFO]: [STDERR]:       at net.minecraft.server.Main.main(Main.java:147)
[11:54:09] [main/INFO]: [STDERR]:       ... 14 more
[11:54:09] [main/INFO]: [STDERR]: Caused by: java.lang.IllegalArgumentException: Multiple entries with same key: _comment======================================= and _comment=======================================
[11:54:09] [main/INFO]: [STDERR]:       at com.google.common.collect.ImmutableMap.checkNoConflict(ImmutableMap.java:186)
[11:54:09] [main/INFO]: [STDERR]:       at com.google.common.collect.RegularImmutableMap.checkNoConflictInKeyBucket(RegularImmutableMap.java:102)
[11:54:09] [main/INFO]: [STDERR]:       at com.google.common.collect.RegularImmutableMap.fromEntryArray(RegularImmutableMap.java:88)
[11:54:09] [main/INFO]: [STDERR]:       at com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:359)
[11:54:09] [main/INFO]: [STDERR]:       at net.minecraft.class_2477.method_29429(class_2477.java:45)
[11:54:09] [main/INFO]: [STDERR]:       at net.minecraft.class_2477.<clinit>(class_2477.java:33)
[11:54:09] [main/INFO]: [STDERR]:       ... 35 more
 ```
 - Detailed reproduction steps: on clients it works fine with HQM but on servers there is a compatibility bug.
 - HQM Version 5.7.2

**Comment by SquidDev** [comment]
Looks like both mods patch `MixinLanguage` to load the JSON files, which conflicts there's duplicate entries.

Don't know what the appropriate thing to do here is, without coordinating between all mods with this mixin. I do really wonder if it's worth submitting this patch upstream and then removing it from all other mods.

**Edit:** Looks like this was removed in https://github.com/lorddusk/HQM/pull/621, so this should be fixed in the next HQM release.

**Comment by Merith-TK** [comment]
Can you please test this?

**Comment by MSandro** [comment]
Thanks.
I will test it one the HQM Team release the new version to CurseForge.

**Comment by Merith-TK** [comment]
Any update? Otherwise I will close the issue.

**Comment by SquidDev** [comment]
Worth noting that in 1.18, 482ed6f6b5c86dc4ebf424153d41dde9335c4777 should have fixed this too.

**Comment by MSandro** [comment]
Solved
