### ISSUE TITLE
Server Crashing on boot with mod installed 

### ISSUE THREAD

**Issue by bobstar3233** [cc-tweaked/cc-restitched#36]
```
[16:10:32] [main/INFO]: Adding serverside commands..
[16:10:33] [main/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.ExceptionInInitializerError
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:610) ~[fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.12.12.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:66) [fabric-loader-0.12.12.jar:?]
Caused by: java.lang.ExceptionInInitializerError
	at net.minecraft.class_2588.method_11025(class_2588.java:43) ~[server-intermediary.jar:?]
	at net.minecraft.class_2588.method_27659(class_2588.java:145) ~[server-intermediary.jar:?]
	at net.minecraft.class_2561.method_27657(class_2561.java:96) ~[server-intermediary.jar:?]
	at net.minecraft.class_5348.getString(class_5348.java:91) ~[server-intermediary.jar:?]
	at net.minecraft.class_2561.getString(class_2561.java:39) ~[server-intermediary.jar:?]
	at com.mojang.brigadier.exceptions.CommandSyntaxException.<init>(CommandSyntaxException.java:27) ~[brigadier-1.0.18.jar:?]
	at com.mojang.brigadier.exceptions.SimpleCommandExceptionType.createWithContext(SimpleCommandExceptionType.java:21) ~[brigadier-1.0.18.jar:?]
	at com.mojang.brigadier.StringReader.readDouble(StringReader.java:142) ~[brigadier-1.0.18.jar:?]
	at net.minecraft.class_2278.method_9743(class_2278.java:41) ~[server-intermediary.jar:?]
	at net.minecraft.class_2280.method_9750(class_2280.java:87) ~[server-intermediary.jar:?]
	at net.minecraft.class_2277.method_9738(class_2277.java:54) ~[server-intermediary.jar:?]
	at net.minecraft.class_2277.parse(class_2277.java:21) ~[server-intermediary.jar:?]
	at com.mojang.brigadier.tree.ArgumentCommandNode.isValidInput(ArgumentCommandNode.java:91) ~[brigadier-1.0.18.jar:?]
	at com.mojang.brigadier.tree.CommandNode.findAmbiguities(CommandNode.java:102) ~[brigadier-1.0.18.jar:?]
	at com.mojang.brigadier.tree.CommandNode.findAmbiguities(CommandNode.java:113) ~[brigadier-1.0.18.jar:?]
	at com.mojang.brigadier.tree.CommandNode.findAmbiguities(CommandNode.java:113) ~[brigadier-1.0.18.jar:?]
	at com.mojang.brigadier.CommandDispatcher.findAmbiguities(CommandDispatcher.java:695) ~[brigadier-1.0.18.jar:?]
	at net.minecraft.class_2170.<init>(class_2170.java:246) ~[server-intermediary.jar:?]
	at net.minecraft.class_5350.<init>(class_5350.java:39) ~[server-intermediary.jar:?]
	at net.minecraft.class_5350.method_29466(class_5350.java:88) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:159) ~[server-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608) ~[fabric-loader-0.12.12.jar:?]
	... 7 more
Caused by: java.lang.IllegalArgumentException: Multiple entries with same key: block.minecraft.nether_wart_block=Crimson Wart Block and block.minecraft.nether_wart_block=Nether Wart Block
	at com.google.common.collect.ImmutableMap.conflictException(ImmutableMap.java:376) ~[guava-31.0.1-jre.jar:?]
	at com.google.common.collect.ImmutableMap.checkNoConflict(ImmutableMap.java:370) ~[guava-31.0.1-jre.jar:?]
	at com.google.common.collect.RegularImmutableMap.checkNoConflictInKeyBucket(RegularImmutableMap.java:153) ~[guava-31.0.1-jre.jar:?]
	at com.google.common.collect.RegularImmutableMap.fromEntryArray(RegularImmutableMap.java:115) ~[guava-31.0.1-jre.jar:?]
	at com.google.common.collect.ImmutableMap$Builder.buildOrThrow(ImmutableMap.java:574) ~[guava-31.0.1-jre.jar:?]
	at com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:538) ~[guava-31.0.1-jre.jar:?]
	at net.minecraft.class_2477.method_29429(class_2477.java:45) ~[server-intermediary.jar:?]
	at net.minecraft.class_2477.<clinit>(class_2477.java:33) ~[server-intermediary.jar:?]
	at net.minecraft.class_2588.method_11025(class_2588.java:43) ~[server-intermediary.jar:?]
	at net.minecraft.class_2588.method_27659(class_2588.java:145) ~[server-intermediary.jar:?]
	at net.minecraft.class_2561.method_27657(class_2561.java:96) ~[server-intermediary.jar:?]
	at net.minecraft.class_5348.getString(class_5348.java:91) ~[server-intermediary.jar:?]
	at net.minecraft.class_2561.getString(class_2561.java:39) ~[server-intermediary.jar:?]
	at com.mojang.brigadier.exceptions.CommandSyntaxException.<init>(CommandSyntaxException.java:27) ~[brigadier-1.0.18.jar:?]
	at com.mojang.brigadier.exceptions.SimpleCommandExceptionType.createWithContext(SimpleCommandExceptionType.java:21) ~[brigadier-1.0.18.jar:?]
	at com.mojang.brigadier.StringReader.readDouble(StringReader.java:142) ~[brigadier-1.0.18.jar:?]
	at net.minecraft.class_2278.method_9743(class_2278.java:41) ~[server-intermediary.jar:?]
	at net.minecraft.class_2280.method_9750(class_2280.java:87) ~[server-intermediary.jar:?]
	at net.minecraft.class_2277.method_9738(class_2277.java:54) ~[server-intermediary.jar:?]
	at net.minecraft.class_2277.parse(class_2277.java:21) ~[server-intermediary.jar:?]
	at com.mojang.brigadier.tree.ArgumentCommandNode.isValidInput(ArgumentCommandNode.java:91) ~[brigadier-1.0.18.jar:?]
	at com.mojang.brigadier.tree.CommandNode.findAmbiguities(CommandNode.java:102) ~[brigadier-1.0.18.jar:?]
	at com.mojang.brigadier.tree.CommandNode.findAmbiguities(CommandNode.java:113) ~[brigadier-1.0.18.jar:?]
	at com.mojang.brigadier.tree.CommandNode.findAmbiguities(CommandNode.java:113) ~[brigadier-1.0.18.jar:?]
	at com.mojang.brigadier.CommandDispatcher.findAmbiguities(CommandDispatcher.java:695) ~[brigadier-1.0.18.jar:?]
	at net.minecraft.class_2170.<init>(class_2170.java:246) ~[server-intermediary.jar:?]
	at net.minecraft.class_5350.<init>(class_5350.java:39) ~[server-intermediary.jar:?]
	at net.minecraft.class_5350.method_29466(class_5350.java:88) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:159) ~[server-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608) ~[fabric-loader-0.12.12.jar:?]
	... 7 more
```

**Comment by bobstar3233** [comment]
[2021-12-17-6.log](https://github.com/cc-tweaked/cc-restitched/files/7736460/2021-12-17-6.log)
full file for log

**Comment by toad-dev** [comment]
482ed6f6b5c86dc4ebf424153d41dde9335c4777 should fix this. I'll notify you when the next release happens so you can retest.

**Comment by JSJBDEV** [comment]
I had this problem but with splash potion of levitation, I should now receive messages here when it gets updated, thanks :)

**Comment by toad-dev** [comment]
> I had this problem but with splash potion of levitation, I should now receive messages here when it gets updated, thanks :)

Like it crashed when you threw the splash potion? That sounds like a different bug. Can you upload logs?

**Comment by JSJBDEV** [comment]
No it crashed in the same way but it reported splash potion of levitation rather than crimson wart block (as seen from this extract above) `
Caused by: java.lang.IllegalArgumentException: Multiple entries with same key: block.minecraft.nether_wart_block=Crimson Wart Block and block.minecraft.nether_wart_block=Nether Wart Block`

**Comment by toad-dev** [comment]
okay yes the fix should cover that sorry for the confusion.

**Comment by toad-dev** [comment]
[This](https://github.com/cc-tweaked/cc-restitched/releases/tag/v1.18.1-1.99.2-alpha1-ccr) release should fix this issue. Can you test again and report back?

**Comment by bobstar3233** [comment]
> [This](https://github.com/cc-tweaked/cc-restitched/releases/tag/v1.18.1-1.99.2-alpha1-ccr) release should fix this issue. Can you test again and report back?

server boots just making duplicate profile to test client joining

**Comment by bobstar3233** [comment]
Has fixed issues
