### ISSUE TITLE
Monitor issues on server

### ISSUE THREAD

**Issue by ethsanders** [cc-tweaked/cc-restitched#45]
### Minecraft Version

1.18.x

### Version

1.99.1

### Details

When using monitors on server, they will not display any output. They won't display when using peripheral, nor when using the monitor command from the terminal. 
Furthermore, occasionally there will be a server crash when breaking a monitor. Log message below.
```
05:45:44] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NoSuchMethodError: 'void dan200.computercraft.shared.peripheral.monitor.ClientMonitor.destroy()'
        at dan200.computercraft.shared.peripheral.monitor.TileMonitor.onChunkUnloaded(TileMonitor.java:102) ~[cc-restitched-1.99.1.jar:?]
        at dan200.computercraft.shared.proxy.ComputerCraftProxyCommon.lambda$registerHandlers$6(ComputerCraftProxyCommon.java:123) ~[cc-restitched-1.99.1.jar:?]
        at net.fabricmc.fabric.api.event.lifecycle.v1.ServerBlockEntityEvents.lambda$static$2(ServerBlockEntityEvents.java:66) ~[fabric-lifecycle-events-v1-1.4.10+c15ca33514-d
830d5ce9751719.jar:?]
        at net.minecraft.class_2818.handler$zcg000$onRemoveBlockEntity(class_2818.java:789) ~[server-intermediary.jar:?]
        at net.minecraft.class_2818.method_12041(class_2818.java:393) ~[server-intermediary.jar:?]
        at net.minecraft.class_1937.method_8544(class_1937.java:552) ~[server-intermediary.jar:?]
        at net.minecraft.class_4970.method_9536(class_4970.java:158) ~[server-intermediary.jar:?]
        at dan200.computercraft.shared.common.BlockGeneric.method_9536(BlockGeneric.java:44) ~[cc-restitched-1.99.1.jar:?]
        at net.minecraft.class_4970$class_4971.method_26197(class_4970.java:913) ~[server-intermediary.jar:?]
        at net.minecraft.class_2818.method_12010(class_2818.java:250) ~[server-intermediary.jar:?]
        at net.minecraft.class_1937.method_30092(class_1937.java:213) ~[server-intermediary.jar:?]
        at net.minecraft.class_1937.method_8652(class_1937.java:198) ~[server-intermediary.jar:?]
        at net.minecraft.class_1937.method_8650(class_1937.java:273) ~[server-intermediary.jar:?]
        at net.minecraft.class_3225.method_14266(class_3225.java:249) ~[server-intermediary.jar:?]
        at net.minecraft.class_3225.method_21717(class_3225.java:221) ~[server-intermediary.jar:?]
        at net.minecraft.class_3225.method_14263(class_3225.java:154) ~[server-intermediary.jar:?]
        at net.minecraft.class_3244.method_12066(class_3244.java:1019) ~[server-intermediary.jar:?]
        at net.minecraft.class_2846.method_12361(class_2846.java:34) ~[server-intermediary.jar:?]
        at net.minecraft.class_2846.method_11054(class_2846.java:8) ~[server-intermediary.jar:?]
        at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[server-intermediary.jar:?]
        at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_18859(class_1255.java:151) ~[server-intermediary.jar:?]
        at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:780) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:162) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_16075(class_1255.java:125) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:762) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:756) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_5383(class_1255.java:110) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:740) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:688) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
```
Neither of these issues were reproducible on singleplayer.

**Comment by Merith-TK** [comment]
Could provide screenshots of ingame so we can attempt to accurately reproduce it?

Along with the full logs of the server? `latest.log`

Open the server, join, reproduce errors, shutdown server. (or cause a crash,) and save and upload the logs to https://mclo.gs (I suggest this one as it highlights text properly and censors stuff like. IP's)

This will help us with identifying possible conflicts or other errors that we need to fix

**Comment by ethsanders** [comment]
https://streamable.com/3vrjr6 monitors not running
https://mclo.gs/dIgUNGu logs attatched for the above case, but they aren't very telling.

Had trouble reproducing the monitor crashing server. It happened when I logged onto the server, but I didn't get a chance to record. I will add a video if I find it, but logs of the case where it happened can be found here: https://mclo.gs/yFBAd45

**Comment by ethsanders** [comment]
Fixed, thanks!
