### ISSUE TITLE
Mod failed to load in 1.17.1 due to depends fabric (but fabric is installed)

### ISSUE THREAD

**Issue by caffeineaddiction** [cc-tweaked/cc-restitched#6]
## Useful information to include:
 - Minecraft version: 1.17.1
 - CC: Restitched version: 1.97.1-beta
 - Logs: These will be located in the `logs/` directory of your Minecraft instance. Please upload them as a gist or directly into this editor.

Error:
```
[init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x 9 1000 1000 4096 Oct 25 15:45 /data'
[init] Resolved version given LATEST into 1.17.1
[init] Resolving type given FABRIC
[init] server.properties already created, skipping
[init] Checking for JSON files.
[init] Setting initial memory to 1G and max to 1G
[init] Starting the Minecraft server...
[16:13:43] [INFO] [FabricLoader/GameProvider]: Loading for game Minecraft 1.17.1
[16:13:44] [main/INFO]: Loading for game Minecraft 1.17.1
[16:13:44] [main/WARN]: Mod resolution failed
[16:13:44] [main/INFO]: Immediate reason: [HARD_DEP_NO_CANDIDATE computercraft 1.97.1-beta {depends fabric @ [*]}, ROOT_FORCELOAD_SINGLE computercraft 1.97.1-beta]
[16:13:44] [main/INFO]: Reason: [HARD_DEP computercraft 1.97.1-beta {depends fabric @ [*]}]
[16:13:44] [main/INFO]: Fix: add [add:fabric 1 ([(-∞,∞)])], remove [], replace []
[16:13:44] [main/ERROR]: A critical error occurred
net.fabricmc.loader.impl.discovery.ModResolutionException: Mod resolution encountered an incompatible mod set! A potential solution has been determined:
         - Install fabric 1 (later versions might work too).
Unmet dependency listing:
         - Mod 'CC:Restitched' (computercraft) requires any version of fabric, which is missing!
        at net.fabricmc.loader.impl.discovery.ModResolver.findCompatibleSet(ModResolver.java:183) ~[fabric-server-1.17.1.jar:?]
        at net.fabricmc.loader.impl.discovery.ModResolver.resolve(ModResolver.java:48) ~[fabric-server-1.17.1.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.setup(FabricLoaderImpl.java:203) ~[fabric-server-1.17.1.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:183) [fabric-server-1.17.1.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:119) [fabric-server-1.17.1.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) [fabric-server-1.17.1.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-server-1.17.1.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:72) [fabric-server-1.17.1.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:98) [fabric-server-1.17.1.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:60) [fabric-server-1.17.1.jar:?]
2021-10-25T16:13:44.369Z        WARN    mc-server-runner        sub-process failed      {"exitCode": 1}
2021-10-25T16:13:44.369Z        INFO    mc-server-runner        Done
```

Same settings w/ out cc-restitched
```
[init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x 9 1000 1000 4096 Oct 25 15:45 /data'
[init] Resolved version given LATEST into 1.17.1
[init] Resolving type given FABRIC
[init] server.properties already created, skipping
[init] Checking for JSON files.
[init] Setting initial memory to 1G and max to 1G
[init] Starting the Minecraft server...
[16:17:04] [INFO] [FabricLoader/GameProvider]: Loading for game Minecraft 1.17.1
[16:17:05] [main/INFO]: Loading for game Minecraft 1.17.1
[16:17:05] [main/INFO]: Loading 4 mods:
        - fabricloader 0.12.3
        - java 16
        - lithium 0.7.4
        - minecraft 1.17.1
[16:17:05] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.4 Source=file:/data/fabric-server-1.17.1.jar Service=Knot/Fabric Env=SERVER
[16:17:05] [main/INFO]: Compatibility level set to JAVA_16
[16:17:05] [main/INFO]: Loaded configuration file for Lithium: 86 options available, 0 override(s) found
[16:17:06] [main/WARN]: Configuration conflict: there is more than one oshi.properties file on the classpath
[16:17:06] [main/WARN]: Configuration conflict: there is more than one oshi.architecture.properties file on the classpath
[16:17:14] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[16:17:15] [main/WARN]: Ambiguity between arguments [teleport, location] and [teleport, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[16:17:15] [main/WARN]: Ambiguity between arguments [teleport, location] and [teleport, targets] with inputs: [0.1 -0.5 .9, 0 0 0]
[16:17:15] [main/WARN]: Ambiguity between arguments [teleport, destination] and [teleport, targets] with inputs: [Player, 0123, @e, dd12be42-52a9-4a91-a8a1-11c01849e498]
[16:17:15] [main/WARN]: Ambiguity between arguments [teleport, targets] and [teleport, destination] with inputs: [Player, 0123, dd12be42-52a9-4a91-a8a1-11c01849e498]
[16:17:15] [main/WARN]: Ambiguity between arguments [teleport, targets, location] and [teleport, targets, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[16:17:15] [main/INFO]: Reloading ResourceManager: Default, bukkit
[16:17:17] [Worker-Main-12/INFO]: Loaded 7 recipes
[16:17:17] [Worker-Main-12/INFO]: Loaded 1137 advancements
[16:17:20] [Server thread/INFO]: Starting minecraft server version 1.17.1
[16:17:20] [Server thread/INFO]: Loading properties
[16:17:20] [Server thread/INFO]: Default game type: SURVIVAL
[16:17:20] [Server thread/INFO]: Generating keypair
[16:17:20] [Server thread/INFO]: Starting Minecraft server on *:25565
[16:17:21] [Server thread/INFO]: Using epoll channel type
[16:17:21] [Server thread/INFO]: Preparing level "world"
[16:17:21] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[16:17:23] [Worker-Main-11/INFO]: Preparing spawn area: 0%
[16:17:23] [Worker-Main-11/INFO]: Preparing spawn area: 0%
[16:17:23] [Worker-Main-8/INFO]: Preparing spawn area: 0%
[16:17:23] [Worker-Main-10/INFO]: Preparing spawn area: 0%
[16:17:23] [Worker-Main-12/INFO]: Preparing spawn area: 0%
[16:17:24] [Worker-Main-13/INFO]: Preparing spawn area: 0%
[16:17:24] [Worker-Main-14/INFO]: Preparing spawn area: 0%
[16:17:25] [Worker-Main-12/INFO]: Preparing spawn area: 0%
[16:17:25] [Worker-Main-11/INFO]: Preparing spawn area: 2%
[16:17:26] [Worker-Main-13/INFO]: Preparing spawn area: 4%
[16:17:26] [Worker-Main-11/INFO]: Preparing spawn area: 4%
[16:17:27] [Worker-Main-10/INFO]: Preparing spawn area: 8%
[16:17:27] [Worker-Main-8/INFO]: Preparing spawn area: 14%
[16:17:28] [Worker-Main-12/INFO]: Preparing spawn area: 34%
[16:17:28] [Worker-Main-11/INFO]: Preparing spawn area: 48%
[16:17:29] [Worker-Main-13/INFO]: Preparing spawn area: 63%
[16:17:29] [Worker-Main-14/INFO]: Preparing spawn area: 76%
[16:17:30] [Worker-Main-11/INFO]: Preparing spawn area: 89%
[16:17:30] [Worker-Main-12/INFO]: Preparing spawn area: 99%
[16:17:34] [Server thread/INFO]: Time elapsed: 12298 ms
[16:17:34] [Server thread/INFO]: Done (12.637s)! For help, type "help"
[16:17:34] [Server thread/INFO]: Starting remote control listener
[16:17:34] [Server thread/INFO]: Thread RCON Listener started
[16:17:34] [Server thread/INFO]: RCON running on 0.0.0.0:25575
[16:17:36] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 2165ms or 43 ticks behind
[16:17:58] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 6944ms or 138 ticks behind
```

 - Detailed reproduction steps: sometimes I can spot a bug pretty easily, but often it's much more obscure. The more information I have to help reproduce it, the quicker it'll get fixed.
 
 I am running it in a docker container, logs came from `docker logs -f fabric`
My startup file looks like:

```
docker stop fabric
docker rm fabric
docker run --name fabric \
  -d --restart=always \
  -p 25555:25565 \
  -v /opt/data/fabric-minecraft:/data \
  -e TYPE=FABRIC \
  -e EULA=true \
  itzg/minecraft-server
```

If I remove CC: Restitched from the mod folder, server starts up fine.  I am pretty sure I have it setup correctly because I have the fabric version of lithium installed, and it seems to be loading in and working.

**Comment by K0-RR** [comment]
You need Fabric API which is a mod (addon to Fabric Loader which you installed)

**Comment by caffeineaddiction** [comment]
@RDKRACZ  thank you, that solved it ... sorry, im a bit new to all this stuff
